//! `airc-wire` — the single well-defined binary codec for
//! [`airc_bus::Envelope`], airc's wire + IPC data plane.
//!
//! # Why a binary FlatBuffer
//!
//! airc is a media-stream bus (WebRTC video/audio, 60-90Hz avatar pose
//! data) *and* a durable chat bus. The encoding has to be a proper binary
//! encoding — not JSON / escapes — and the opaque [`Envelope::payload`]
//! must be forwarded **verbatim, zero-copy**: never decoded, re-encoded,
//! or copied. The render loop is sacred.
//!
//! This crate is that encoding. It is built on [`planus`] — a pure-Rust
//! FlatBuffers compiler and runtime that produces spec-compliant
//! FlatBuffers bytes with **no C++ `flatc`** at build time, so CI stays
//! green on ubuntu/macos/windows with the stock Rust toolchain.
//!
//! ## Source of truth & codegen
//!
//! The `.fbs` schema in `src/schema/wire.fbs` is the source of truth. The
//! Rust accessors in `src/wire_generated.rs` are produced from it by the
//! `planus` CLI and **committed** (deterministic, no `build.rs`):
//!
//! ```text
//! planus rust -o crates/airc-wire/src/wire_generated.rs \
//!     crates/airc-wire/src/schema/wire.fbs
//! ```
//!
//! # API
//!
//! - [`encode`] builds the FlatBuffer once — the one sanctioned encode.
//! - [`WireEnvelope`] is a zero-copy read view over `&[u8]`: it exposes the
//!   routing fields (kind, delivery, channel, seq, correlation_id, headers)
//!   and crucially [`WireEnvelope::payload`], a slice INTO the buffer (no
//!   copy). Routing reads fields in place without materializing the whole
//!   [`Envelope`].
//! - [`decode`] reconstructs the Rust [`Envelope`]. Small metadata fields
//!   are read out (cheap); the big `payload` is reconstructed with
//!   [`bytes::Bytes::slice_ref`], which shares the decoded buffer's
//!   allocation — **never a copy**.

// The generated FlatBuffers accessors. Kept verbatim from the `planus`
// CLI so it can be regenerated byte-for-byte from `schema/wire.fbs`. The
// generated code is not hand-written library code, so the production
// no-silent-fallback lint families do not apply to it; we scope the
// allows to this `mod` declaration rather than editing the generated file.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::wildcard_enum_match_arm,
    clippy::undocumented_unsafe_blocks,
    unused_qualifications,
    missing_docs
)]
#[rustfmt::skip]
mod wire_generated;

mod codec;
mod error;

pub use codec::{decode, encode, WireEnvelope, WireHeaders};
pub use error::WireError;

// Re-export the generated FlatBuffers types under a `fb` module for any
// consumer that wants to work with the raw schema types directly. The
// codec API above is the sanctioned surface; this is an escape hatch.
pub mod fb {
    //! The raw `planus`-generated FlatBuffers types for the airc wire
    //! schema (`airc.wire` namespace). Most consumers want the [`encode`],
    //! [`decode`], and [`WireEnvelope`] surface instead.
    //!
    //! [`encode`]: crate::encode
    //! [`decode`]: crate::decode
    //! [`WireEnvelope`]: crate::WireEnvelope
    pub use crate::wire_generated::airc::wire::{
        DeliveryClass as FbDeliveryClass, Envelope as FbEnvelope, EnvelopeRef, Header as FbHeader,
        HeaderRef, Kind as FbKind, TargetTag as FbTargetTag, Uuid as FbUuid, UuidRef,
    };
}
